### PR TITLE
#8 Fixed the issue where the plugins were not yet registered

### LINKED ISSUE #8: iOS Can not use other plugins in the background
No Method Implemented for ... plugin

Related Resources:
https://github.com/flutter/flutter/issues/62006
https://github.com/fluttercommunity/flutter_workmanager/blob/master/ios/Classes/WorkmanagerPlugin.m
https://github.com/fluttercommunity/flutter_workmanager/blob/master/example/ios/Runner/AppDelegate.swift#L14

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
Fixed #8

### CODE REVIEW

**Review by DimmyMaenhout — APPROVED** [review]

**Review by DimmyMaenhout — DISMISSED** [review]

File: example/lib/main.dart [hunk 1]
```diff
@@ -1,10 +1,13 @@
...
+import 'dart:io';
+import 'dart:math';
 
 import 'package:background_location_tracker/background_location_tracker.dart';
 import 'package:flutter/material.dart';
+import 'package:flutter_local_notifications/flutter_local_notifications.dart';
 import 'package:permission_handler/permission_handler.dart';
 
-void _backgroundCallback() => BackgroundLocationTrackerManager.handleBackgroundUpdated((data) => Repo().update(data));
+void _backgroundCallback() => BackgroundLocationTrackerManager.handleBackgroundUpdated((data) async => Repo().update(data));
```
Comment (DimmyMaenhout) [inline example/lib/main.dart:10]: is the async explicitly required?

**Review by DimmyMaenhout — COMMENTED** [review]
for the file main.dart is the async on line 10 required?

File: example/lib/main.dart (hunk 1 above)
Comment (vanlooverenkoen) [reply example/lib/main.dart:10]: Yes. Because we want to wait on that result before we cleanup the flutter resources in iOS

**Review by DimmyMaenhout — APPROVED** [review]
