### PR TITLE
Bugfix/crash ios flutter engine rewrite

### LINKED ISSUE #25: Random out of memory issues iOS
Sometimes we can use our app for 30 min
Sometimes the app crashes after 1 min

Could be related to the flutter engine that is used in the native iOS code

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
Fixed #25

### CODE REVIEW

**Review by NicolaChimerapps — APPROVED** [review]

**Review by HannesVDB — APPROVED** [review]

File: ios/Classes/SwiftBackgroundLocationTrackerPlugin.swift [hunk 1]
```diff
@@ -35,6 +41,56 @@ extension SwiftBackgroundLocationTrackerPlugin: FlutterPlugin {
...
+            self.flutterEngine = flutterEngine
+        }
+        return flutterEngine
+    }
+    
+    public static func initBackgroundMethodChannel(flutterEngine: FlutterEngine) {
+        if (backgroundMethodChannel == nil) {
+            CustomLogger.log(message: "backgroundMethodChannel is nil, we will create a new background method channel.")
+            backgroundMethodChannel = FlutterMethodChannel(name: SwiftBackgroundLocationTrackerPlugin.BACKGROUND_CHANNEL_NAME, binaryMessenger: flutterEngine.binaryMessenger)
+            backgroundMethodChannel!.setMethodCallHandler { (call, result) in
```
Comment (DimmyMaenhout) [inline ios/Classes/SwiftBackgroundLocationTrackerPlugin.swift:65]: It's better to unwrap the optional with a if let or guard let, now the app can crash when backgroundMethodChannel is nil for some reason.

File: ios/Classes/SwiftBackgroundLocationTrackerPlugin.swift [hunk 2]
```diff
@@ -35,6 +41,56 @@ extension SwiftBackgroundLocationTrackerPlugin: FlutterPlugin {
...
+                switch call.method {
+                case BackgroundMethods.initialized.rawValue:
+                    initializedBackgroundCallbacks = true
+                    let locationData = SwiftBackgroundLocationTrackerPlugin.locationData
```
Comment (DimmyMaenhout) [inline ios/Classes/SwiftBackgroundLocationTrackerPlugin.swift:69]: This constant isn't needed, SwiftBackgroundTrackerPlugin.locationData can be used directly on the line below

**Review by DimmyMaenhout — DISMISSED** [review]

**Review by NicolaChimerapps — APPROVED** [review]

**Review by DimmyMaenhout — APPROVED** [review]

**Review by DimmyMaenhout — APPROVED** [review]
